default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("MAX_THREADS") { 5 } %>
  
development:
  <<: *default
  database: floridacovid_development

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>